### PR TITLE
adding shapely library to packages

### PR DESCRIPTION
**Pull request by waliens**
useful for various operations including parsing the WKT strings from csv

### CODE REVIEW

**Comment by pjbull** [comment]
Thanks @waliens! You can ignore the failures right now, they look unrelated to your change.

One request: could you add `shapely` to the packages that we test as well:
https://github.com/drivendataorg/sfp-cervical-biopsy-runtime/blob/37ae0b5e28ae834b92c9ecea8bcf8bae20b4c378/runtime/tests/test-installs.py#L12

Also, curious why you want `shapely` in the inference runtime. There are no annotations available for the test images, so we aren't providing any WKT data. Will your algorithm be generating these shapes or regions as WKT as part of inference?

**Comment by pjbull** [comment]
Also, we've made a change to the master branch that should make the checks here pass. Could you reabse this change onto the latest from master? There shouldn't be any conflicts since it was just a change to the GitHub Actions configuration.

**Comment by waliens** [comment]
A step of my algorithm will indeed generate shapes representing the tissue regions in a slide (to avoid processing background). Working with shapely would greatly help for handling those shapes. 

I am going to rebase my fork asap, thanks.

**Comment by pjbull** [comment]
Thanks @waliens! I pushed an update to merge with #14, which went in before this. Once the build succeeds here, I will move accept the PR.

**Pull request merged**
